- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: DevsecOps with AWS # equals to COURSE=Ansiblr in shell, shell we refer $var or ${var}
    DURATION: 10HR
    TRAINER: Sivakumar
  tasks:
  - name: print course infromation
    vars:
    COURSE: Ansible
    ansible.builtin.debug:
    #vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{DURATION}}, Trainer: {{TRAINER}}"
      
  - name: print course infromation again
    ansible.builtin.debug:
    #vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{DURATION}}, Trainer: {{TRAINER}}"