- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course infromation
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{DURATION}}, trainer{{TRAINER}}"